### PR TITLE
Capitalized the letter W in @EmailTemplates/WelcomeAboard and Added T…

### PR DESCRIPTION
**Pull request by cvalderrama1991**
Capitalized the letter W in @EmailTemplates/WelcomeAboard and Added Type for WelcomeAboard function props

### CODE REVIEW

**Comment by robahtou** [comment]
@cvalderrama1991 let's sync up on this. Seems like the linting is getting through and making changes to 70 files. Also, make sure to merge main.

**Comment by cvalderrama1991** [comment]
I think this is also my fault. When I used the linter, I formatted all the files instead of just the files inside the "src" folder. I can go back and make the corrections. Also can you remind me again if you like to use single or double quotes?

**Comment by robahtou** [comment]
I mean implementation context. like, where are you adding double quotes or single quotes.

Ignore the linter formatting (do not use prettier). In other words, don't lint anything. If anything, your IDE linter for the react-atx project. 

I'm still working on configuring biome.js linter, so until that is done just ignore/disable all linter rules.

**Comment by cvalderrama1991** [comment]
I'll have to check how I have my settings. Okay I'll just disable everything in IDE for now.

**Pull request closed without merging**
